### ISSUE TITLE
'npm install' won't work due to broken dependencies

### ISSUE THREAD

**Issue by CramericaIndustries** [tobinbradley/mapbox-gl-style-editor#2]
npm v6.13.7;
node v13.10.1;

Tried to install it on Windows first, but I've read that mapnik discontinued Windows support, so I switched over to Debian 10. Unfortunately I'm getting that 403 error over there as well. 
Already tried to do `npm update`, but haven't had success with that either.

```
root@debian10-docker:/docker/mapbox-gl-style-editor# npm i

> fontnik@0.4.8 install /docker/mapbox-gl-style-editor/node_modules/fontnik
> node-pre-gyp install --fallback-to-build=false || (source ./scripts/install_mason.sh && node-pre-gyp install --build-from-source)

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/usr/bin/node',
node-pre-gyp verb cli   '/docker/mapbox-gl-style-editor/node_modules/fontnik/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build=false'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@13.10.1 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/docker/mapbox-gl-style-editor/node_modules/fontnik/lib/fontnik.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v79-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v79-linux-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v79-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/docker/mapbox-gl-style-editor/node_modules/fontnik/node_modules/node-pre-gyp/lib/install.js:98:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:328:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/docker/mapbox-gl-style-editor/node_modules/fontnik/node_modules/node-pre-gyp/node_modules/request/request.js:986:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:316:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:479:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:316:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:297:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:273:9)
node-pre-gyp ERR! System Linux 4.19.0-8-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/docker/mapbox-gl-style-editor/node_modules/fontnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /docker/mapbox-gl-style-editor/node_modules/fontnik
node-pre-gyp ERR! node -v v13.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v79-linux-x64.tar.gz
sh: 1: source: not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mapbox-gl-editor@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/abbrev' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/ansi-regex' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/aproba' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/balanced-match' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/chownr' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/code-point-at' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/concat-map' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/console-control-strings' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/core-util-is' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/deep-extend' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/delegates' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/detect-libc' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/fs.realpath' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/has-unicode' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/inherits' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/ini' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/isarray' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/minimist' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/ms' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/number-is-nan' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/object-assign' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/os-homedir' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/os-tmpdir' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/path-is-absolute' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/process-nextick-args' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/rc/node_modules/minimist' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/rc/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/safe-buffer' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/safer-buffer' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/sax' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/semver' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/set-blocking' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/signal-exit' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/strip-json-comments' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/util-deprecate' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/wrappy' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/yallist' -> '/docker/mapbox-gl-style-editor/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fontnik@0.4.8 install: `node-pre-gyp install --fallback-to-build=false || (source ./scripts/install_mason.sh && node-pre-gyp install --build-from-source)`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fontnik@0.4.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-12T08_15_07_183Z-debug.log

```

**Comment by tobinbradley** [comment]
I'm seeing the same build issue with Node 13 on Manjaro (Arch). Best guess is fontnik isn't compatible with v13. They *should* have prebuilt binaries for v12 so the compile step won't be necessary. That being said, the repo this one points to specifies an older version of fontnik, so it might not have a binary for v12.

There were really two parts to this thing - an interactive style editor, and the tooling to render down fonts and sprites for Mapbox GL. It's the latter that's causing the problems, and if I were building this today I'd use Docker images for those to avoid all the thorny Mapbox compile issues. 

Let me see if I can segment that stuff out so the main thing works.

**Comment by tobinbradley** [comment]
OK. It can be used as a style editor again. It just doesn't do the font and sprite conversion. Now the only dependency is browser-sync.

I'll try to make a Docker image for the mapbox C stuff (fonts, sprites, tippicanoe) so a single Docker image can handle that jazz and nobody will have to worry about building their binaries.

**Comment by CramericaIndustries** [comment]
Thank you very much Tobin!

**Comment by tobinbradley** [comment]
I made another repo with a Dockerfile etc. for the compiled Mapbox C tools (spritezero, fontnik, and tippecanoe) if you needed that kind of stuff. If you're curious, the magic Node version for fontnik and spritezero was 10 :).

[tobinbradley/docker-mapbox-tools](https://github.com/tobinbradley/docker-mapbox-tools)
